### ISSUE TITLE
Regarding documentation of the code

### ISSUE THREAD

**Issue by fnusid** [BingYang-20/SAR-SSL#2]
Hey,
I came across the paper "Self-Supervised Learning of Spatial Acoustic Representation with Cross-Channel Signal Reconstruction and Multi-Channel Conformer". I found the paper to be very insightful, In my current research, I plan to build upon your work. I saw that the full code has not been uploaded, and also it would be very helpful if you can release some documentation on the code. 

Thank you

**Comment by BingYang-20** [comment]
Thank you for your interest! We have recently revised our work based on the reviewer's comments and will be updating our code soon.
